'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { parsePayload } = require('../lib/recovery-transport');
const { loadReviewedView, applyResolutions } = require('../lib/reviewed-resolutions');
const root = path.resolve(__dirname, '../../..');
const audit = path.join(root, 'data/hpt-audit');
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');

test('Lake Huron later exact root and file recheck corrects only the standing template finding', async () => {
  const proof = require(path.join(audit, 'reconciliation-lake-huron-current-proof.json'));
  const pointer = fs.readFileSync(path.join(root, 'cms_data/hpt/pointer-corpus/raw/mylakehuron.com-351626c25224.txt'));
  const sample = fs.readFileSync(path.join(root, proof.retained_sample));
  const parsed = (await parsePayload(sample, 'application/json')).parsed.find(row => row.innerKind === 'json');
  const resolution = require(path.join(audit, 'reviewed-resolutions.json')).find(row => row.ccn === proof.ccn);
  const view = loadReviewedView(audit);
  const row = view.compliance.find(item => item.ccn === proof.ccn);
  const nationwide = require(path.join(audit, 'nationwide-verification.json')).records.find(item => item.ccn === proof.ccn);
  const reconciliation = require(path.join(audit, 'nationwide-reconciliation.json')).records.find(item => item.ccn === proof.ccn);
  assert.equal(proof.ccn, '230031');
  assert.equal(sha(pointer), proof.pointer_sha256);
  assert.equal(sha(sample), proof.retained_sha256);
  assert.ok(pointer.toString('utf8').includes(`mrf-url: ${proof.mrf_url}`));
  assert.equal(sample.length, 262144);
  assert.equal(parsed.mrfHospitalName, 'Lake Huron Medical Center');
  assert.equal(parsed.mrfAddress, proof.declared_address);
  assert.equal(parsed.mrfLicenseState, 'MI');
  assert.equal(parsed.declaredLastUpdated, '2026-09-01');
  assert.equal(parsed.cmsVersion, '3.0');
  assert.equal(row.finding, 'compliant-observed');
  assert.equal(row.mrf_url, proof.mrf_url);
  assert.equal(nationwide.observation_role, 'superseded-retry');
  assert.equal(reconciliation.workstream, 'consistent');
  assert.equal(view.history[proof.ccn].mrf_url, proof.prior_standing_mrf_url);
  const html = fs.readFileSync(path.join(root, 'tracker.html'), 'utf8');
  const open = '<script id="tracker-data" type="application/json">';
  const start = html.indexOf(open), end = html.indexOf('</script>', start);
  const data = JSON.parse(html.slice(start + open.length, end));
  const trackerRow = data.rows.find(item => item[0] === proof.ccn);
  assert.equal(trackerRow[8], proof.mrf_url);
  assert.equal(data.dict.findings[trackerRow[5]], 'compliant-observed');
  const altered = structuredClone(resolution);
  altered.evidence.expected_version = '3.0';
  assert.throws(() => applyResolutions([altered.base], [], [], [altered]), /lacks current, pointer-linked identity/);
});
