'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { parsePayload } = require('../lib/recovery-transport');
const { loadReviewedView, applyResolutions } = require('../lib/reviewed-resolutions');
const root = path.resolve(__dirname, '../../..');
const audit = path.join(root, 'data/hpt-audit');
const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');

test('Park Nicollet Methodist identity is retained with literal file street typo', async () => {
  const proof = require(path.join(audit, 'reconciliation-methodist-address-proof.json'));
  const pointer = fs.readFileSync(path.join(root, 'cms_data/hpt/pointer-corpus/raw/healthpartners.com-02cef7388d09.txt'));
  const sample = fs.readFileSync(path.join(root, proof.retained_sample));
  const parsed = (await parsePayload(sample, 'text/csv')).parsed.find(row => row.innerKind === 'csv');
  const resolution = require(path.join(audit, 'reviewed-resolutions.json')).find(row => row.ccn === proof.ccn);
  const view = loadReviewedView(audit);
  const standing = view.compliance.find(row => row.ccn === proof.ccn);
  const nationwide = require(path.join(audit, 'nationwide-verification.json')).records.find(row => row.ccn === proof.ccn);
  const worklist = require(path.join(audit, 'unresolved-investigation-worklist.json')).records;
  assert.equal(proof.ccn, '240053');
  assert.equal(sha(pointer), proof.pointer_sha256);
  assert.equal(sha(sample), proof.retained_sha256);
  assert.equal(sample.length, 262144);
  assert.ok(pointer.toString('utf8').includes(`mrf-url: ${proof.mrf_url}`));
  assert.equal(parsed.mrfHospitalName, 'Methodist Hospital');
  assert.equal(parsed.mrfAddress, '6500 Exclesior Blvd, St. Louis Park, MN 55426-4702');
  assert.equal(parsed.mrfLicenseState, 'MN');
  assert.equal(parsed.declaredLastUpdated, '2026-03-31');
  assert.equal(parsed.cmsVersion, '3.0.0');
  assert.equal(standing.finding, 'mrf-address-field-conflicts-facility');
  assert.equal(standing.mrf_url, proof.mrf_url);
  assert.equal(nationwide.observation_role, 'superseded-retry');
  assert.equal(worklist.some(row => row.ccn === proof.ccn), false);
  assert.match(view.history[proof.ccn].evidence, /does not name this hospital/);
  const html = fs.readFileSync(path.join(root, 'tracker.html'), 'utf8');
  const open = '<script id="tracker-data" type="application/json">';
  const start = html.indexOf(open), end = html.indexOf('</script>', start);
  const data = JSON.parse(html.slice(start + open.length, end));
  const trackerRow = data.rows.find(row => row[0] === proof.ccn);
  assert.equal(trackerRow[8], proof.mrf_url);
  assert.equal(data.dict.findings[trackerRow[5]], standing.finding);
  assert.match(data.findings.find(row => row.key === standing.finding).label, /address field differs/);
  const altered = structuredClone(resolution);
  altered.evidence.facility_address = altered.evidence.declared_address;
  assert.throws(() => applyResolutions([altered.base], [], [], [altered]), /lacks current, pointer-linked identity/);
});
