'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const {Budget,validateDecision}=require('../lib/recovery-budget');
function budget(t,limit=10){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'hpt-budget-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return new Budget(path.join(dir,'budget.json'),limit);}
test('reservations prevent concurrent overspend and duplicate retries',t=>{const b=budget(t);b.reserve('a','glm',6);assert.throws(()=>b.reserve('b','glm',5));assert.throws(()=>b.reserve('a','glm',1));b.settle('a',2);b.reserve('b','glm',5);assert.equal(b.committed,7);});
test('missing or excessive usage halts paid dispatch and preserves reservation',t=>{const b=budget(t);b.reserve('a','glm',1);assert.throws(()=>b.settle('a',undefined));assert.equal(b.committed,1);assert.throws(()=>b.reserve('b','glm',1));});
test('budget survives restart without resetting spending',t=>{const b=budget(t);b.reserve('a','glm',1);b.settle('a',.5);const c=new Budget(b.file);assert.equal(c.committed,.5);assert.throws(()=>c.reserve('a','glm',1));});
test('model cannot invent evidence IDs or issue unsupported actions',()=>{assert.throws(()=>validateDecision({action:'apply',explanation:'yes',evidence_ids:[]},[]));assert.throws(()=>validateDecision({action:'visit',url:'https://example.org',explanation:'yes',evidence_ids:['invented']},['page-0']));assert.throws(()=>validateDecision({action:'visit',url:'file:///secret',explanation:'yes',evidence_ids:[]},[]));});
test('model URL proposals remain leads and do not contain a promotion verdict',()=>{const d=validateDecision({action:'visit',url:'https://example.org',explanation:'lead',evidence_ids:[]},[]);assert.equal(d.action,'visit');assert.equal(d.accepted,undefined);});
test('browser imports require observed source pages',()=>{const {validateObservation}=require('../recovery-browser');assert.throws(()=>validateObservation({domain:'example.org',checkedAt:'2026-09-09',outcome:'page-read',visited:['https://example.org'],links:[{url:'https://example.org/file.csv',sourcePageUrl:'https://invented.org'}]}));});
test('paid run lock prevents another process from sharing the accounting ledger',t=>{const b=budget(t),{acquireRunLock}=require('../lib/recovery-budget');const file=path.join(path.dirname(b.file),'run.lock'),release=acquireRunLock(file);assert.throws(()=>acquireRunLock(file),/already holds/);release();acquireRunLock(file)();});
